name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v5

    - uses: actions/cache@v4
      with:
        path: |
          target/
        key: ${{ hashFiles('src/**', 'Cargo.toml', 'Cargo.lock') }}

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: cargo

    - name: Cargo Test
      run: |
        cargo test --all-features
